// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
 import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7Mbwkt58izV2pdzpWlpyGKLNo28F85ho',
    appId: '1:1060322466630:android:d05e0cf3bc9a93ceb92347',
    messagingSenderId: '1060322466630',
    projectId: 'newsapp-4ea2d',
    databaseURL: 'https://newsapp-4ea2d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'newsapp-4ea2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3FJRiMA1D5c0otsSpoTNw3IDFBH4M_q4',
    appId: '1:1060322466630:ios:66677bd3f63174b7b92347',
    messagingSenderId: '1060322466630',
    projectId: 'newsapp-4ea2d',
    databaseURL: 'https://newsapp-4ea2d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'newsapp-4ea2d.firebasestorage.app',
    androidClientId: '1060322466630-7b3unkhmg96f4pvkhu62uo6g0q9k7ugc.apps.googleusercontent.com',
    iosClientId: '1060322466630-bqfnnuio3bqlnao896ekg6dplv00qqus.apps.googleusercontent.com',
    iosBundleId: 'com.example.nugrow',
  );

}